runtime: java11
env: standard
runtime_config:
  jdk: openjdk11

env_variables:
  SPRING_PROFILES_ACTIVE: ""

handlers:
  - url: /.*
    script: this field is required, but ignored

manual_scaling:
  instances: 1