runtime: java11
env: standard
runtime_config:
  jdk: openjdk11

env_variables:
  SPRING_PROFILES_ACTIVE: ""

handlers:
  - url: /.*
    script: this field is required, but ignored

service_account: merchant-center-1650186117263@merchant-center-1650186117263.iam.gserviceaccount.com

manual_scaling:
  instances: 1