
runtime: java11
env: standard
runtime_config:
  jdk: openjdk11

env_variables:
  SPRING_PROFILES_ACTIVE: ""

handlers:
  - url: /.*
    script: this field is required, but ignored

manual_scaling:
  instances: 1

network:
  forwarded_ports:
    - 9999/tcp

service_account: merchant-center-1650186117263@merchant-center-1650186117263.iam.gserviceaccount.com